export const siteCopy = {
  landing: {
    eyebrow: 'GEMMS · Musina field atlas',
    title: 'One border town. Two ways of reading movement.',
    lede: 'Musina in Motion brings together two complementary spatial views. The survey atlas shows patterns across the study geography; Narrated Journeys follows ten selected interview accounts as movement unfolds through places, pauses, crossings, work, return and settlement.',
    principle: 'Patterns and stories answer different questions. The survey is used to describe spatial variation among participants; the interview journeys are used to read sequence and lived experience. Neither is used to stand in for the other.',
    surveyKicker: 'Quantitative spatial atlas',
    surveyTitle: 'Explore the Survey Atlas',
    surveyDescription: 'Read regional mobility connections, local survey geography, everyday infrastructure, participatory resources and ward-level patterns from the cleaned GEMMS Musina survey data.',
    journeysKicker: 'Qualitative journey atlas',
    journeysTitle: 'Read Narrated Journeys',
    journeysDescription: 'Follow ten pseudonymised interview journeys stop by stop, from places of origin through border crossings, temporary settlements, work, return and arrival in Musina.',
    contextTitle: 'Pattern and sequence illuminate different parts of migration.',
    contextBody: 'The survey can show how conditions vary across the study geography. Interviews can show how movement accumulates through time and place. Keeping the two forms of evidence connected but analytically distinct makes the atlas more useful — and more honest.',
    footer: 'Musina in Motion · GEMMS spatial atlas',
  },
  survey: {
    eyebrow: 'GEMMS · Musina spatial atlas',
    title: 'Musina in Motion',
    lede: 'A spatial reading of movement, settlement, work and everyday access in a South African border town. The atlas moves across three connected scales: regional mobility, local survey geography, and the resources and services that shape everyday life.',
    primaryAction: 'Open regional mobility',
    secondaryAction: 'Read evidence note',
    cardTitle: 'A field atlas for reading place carefully.',
    cardBody: 'The interface shows patterns by ward, survey block and resource landscape while keeping household locations and individual survey records off the map.',
    metrics: {
      analyzable: 'Analysable survey observations',
      analyzableNote: 'Cleaned survey base used in the spatial summaries.',
      blocks: 'Survey block anchors',
      blocksNote: 'Mapped as broad fieldwork anchors, not household locations.',
      wards: 'Selected wards',
      wardsNote: 'The Musina wards included in the study geography.',
      privacy: 'Household locations shown',
      privacyValue: 'No',
      privacyNote: 'Respondent-level locations remain outside the interface.',
    },
    footer: 'Musina in Motion · GEMMS survey atlas · privacy-screened spatial summaries',
  },
  journeys: {
    eyebrow: 'Selected in-depth interviews · qualitative journey atlas',
    title: 'Narrated Journeys',
    lede: 'Ten selected interview accounts trace how movement into and around Musina unfolds through origin, transit, border crossing, temporary settlement, work, return and adaptation.',
    governance: 'These maps are interpretive reconstructions from selected in-depth interviews. They are not representative statistical claims and they are not GPS traces. Named places show broad journey geography; no household-level locations are displayed.',
    bridge: 'A flow map can show where places connect. A narrated journey shows what happens between them.',
    bridgeBody: 'The ten accounts make visible pauses, border encounters, temporary settlements, repeated movement and changing relationships to place. A direct route can still lead to a highly mobile life; a long or interrupted route can end in more permanent settlement.',
    overviewBody: 'The opening map holds all ten routes together so Musina can first be read as a point of convergence. Choose a person once, then scroll: the map follows the narrated sequence while keeping the wider route visible.',
    footer: 'Musina in Motion · Narrated Journeys · selected interview geographies',
  },
};
